### ISSUE TITLE
Roadmap for DICOM fixtures library

### ISSUE THREAD

**Issue by dang3r** [dang3r/healthcare-tech#8]
# Overview

Create a library for generating DICOM images from scratch.

# Action Items

- [ ] How to share DICOM attribute generation code between the ImageFactory and Examfactory?
  - I could copy and paste the attribute to each class. Simplest.
  - I could create another class that both inherit from. It would have the attributes defined and there would be minimal differences between each clas
  - Encapsulate the attributes set at the exam level in a dictionary, and pass those to the ImageFactory as kwargs
- [ ] Differentiate between create vs build. Create should persist the DICOM to disk (eg. save_as), or to a DICOM SCP
- [ ] Add automatic and manual test cases
- [ ] Add the ability to create a DICOM file with an image of a specific size (eg. 1GB, 100MB).
- [ ] Write test cases
- [ ] Add ability to grab certain attributes from an actual DICOM file and replace other ones.
- [ ] Change all dicom attributes to be set lazily. if a value is set like `AccessionNumber = faker.md5()` during class definition, it will be the same for all instances generated by the factory.
